### ISSUE TITLE
Add option to make QuestBook Soul Bound

### ISSUE THREAD

**Issue by Drethic** [Drethic/QuestBook#18]
*Acceptance Criteria*
- [ ] If this option is enabled the option to give a player a copy of the book must be enabled
- [ ] Add option to disable crafting recipe if Soul Bound option is enabled
- [ ] Book does not duplicate in grave or with popular mods like Gravestone
- [ ] Book returns to player inventory upon respawn

Example code for soul bound can be found here: [EnderIO Enchanting](https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java)

**Comment by ItsKestrel** [comment]
Any progress on this feature? Would love to have this.

**Comment by Drethic** [comment]
With the update to 12.2.x I have reworked the mod and need to port in my work from it's development branch and re-test everything.  I'll post an update as soon as I have it working with 1.10 & 1.12

**Comment by ItsKestrel** [comment]
Awesome, thanks. Looking forward to the 1.12 update!
