### ISSUE TITLE
Add notification to the book when you've completed a quest

### ISSUE THREAD

**Issue by Drethic** [Drethic/QuestBook#2]
- [ ] Quest Notifications disable with config option
- [ ] Works in Single Player
- [ ] Works on Servers (server config overrides client)
