### ISSUE TITLE
Add notification to the book when you've been sent an invite to a party

### ISSUE THREAD

**Issue by Drethic** [Drethic/QuestBook#3]
- [ ] Party Notifications disable with config option
- [ ] Works in Single Player
- [ ] Works on Servers (server config overrides client)

```
public boolean lastStatus = false;

public boolean showInviteNotice(EntityPlayer player)
{
// Only updates the variable every 10 seconds
if(player.ticksExisted%200 != 0)
{
lastStatus = PartyManager.getParty(player.getUniqueID()) == null && PartyManager.getInvites(player.getUniqueID()).size() > 0;
}
return lastStatus;
}
```
