### ISSUE TITLE
Improve Quest Book image

### ISSUE THREAD

**Issue by Drethic** [Drethic/QuestBook#5]
- [x] Find graphic artist
- [x] Have artist increase image from 16 x 16 to 150 x 150 and sharpen
- [x] Replace existing resource with new image

**Comment by Drethic** [comment]
2.1.0-1.7.10 and 2.1.0-1.10 have been released and approved with the new image.  This closes the issue.
