### ISSUE TITLE
Add config option to spawn with new player

### ISSUE THREAD

**Issue by Drethic** [Drethic/QuestBook#6]
- [x] Add Config Option
- [x] Works in Single Player
- [x] Works on Servers (server config overrides client)

**Comment by Dream-Master** [comment]
I hope we get this feature soon because it would be very handy if new Players have the Book with the first start in the Inventory.

**Comment by Drethic** [comment]
I have released version 1.1.0 which has this feature.

**Comment by Dream-Master** [comment]
nice :+1:
